import { createHash, randomBytes } from "crypto"; import { requireEnv, xRedirectUri } from "@/lib/env"; import type { XIdentity } from "@/db/queries/creators";
const AUTH="https://x.com/i/oauth2/authorize"; const TOKEN="https://api.x.com/2/oauth2/token"; const API="https://api.x.com/2";
const b64=(b:Buffer)=>b.toString("base64url");
export function createPkce(){const verifier=b64(randomBytes(48));return{verifier,challenge:b64(createHash("sha256").update(verifier).digest()),state:b64(randomBytes(32))};}
export function getXAuthorizationUrl(input:{state:string;challenge:string}){const p=new URLSearchParams({response_type:"code",client_id:requireEnv("X_CLIENT_ID"),redirect_uri:xRedirectUri(),scope:"tweet.read users.read",state:input.state,code_challenge:input.challenge,code_challenge_method:"S256"});return`${AUTH}?${p}`;}
export async function exchangeXCode(code:string,verifier:string){const id=requireEnv("X_CLIENT_ID");const secret=process.env.X_CLIENT_SECRET;const headers:HeadersInit={"Content-Type":"application/x-www-form-urlencoded"};if(secret)headers.Authorization=`Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`;const body=new URLSearchParams({code,grant_type:"authorization_code",client_id:id,redirect_uri:xRedirectUri(),code_verifier:verifier});const r=await fetch(TOKEN,{method:"POST",headers,body,cache:"no-store"});if(!r.ok)throw new Error(`X token exchange failed: ${r.status} ${await r.text()}`);return await r.json() as {access_token:string;};}
type XResponse={data:{id:string;name:string;username:string;profile_image_url?:string;description?:string;location?:string;public_metrics?:{followers_count:number}}};
function identity(x:XResponse):XIdentity{return{id:x.data.id,username:x.data.username,name:x.data.name,profileImageUrl:x.data.profile_image_url?.replace("_normal","_400x400")??null,description:x.data.description??null,location:x.data.location??null,followers:x.data.public_metrics?.followers_count??0};}
async function lookup(url:string,token:string){const p=new URLSearchParams({"user.fields":"id,name,username,profile_image_url,description,location,public_metrics"});const r=await fetch(`${url}?${p}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok)throw new Error(`X user lookup failed: ${r.status} ${await r.text()}`);return identity(await r.json() as XResponse);}
export const getAuthenticatedXUser=(token:string)=>lookup(`${API}/users/me`,token);
export const getXUserById=(id:string)=>lookup(`${API}/users/${id}`,requireEnv("X_BEARER_TOKEN"));
