import { and, desc, eq, gte } from "drizzle-orm";
import { getDb } from "@/db";
import { creators, products, snapshots, users } from "@/db/schema";
import type { CreatorProfile, LeagueSlug, Plan } from "@/types";
export type XIdentity={id:string;username:string;name:string;profileImageUrl:string|null;description:string|null;location:string|null;followers:number;};
export async function upsertXIdentity(profile:XIdentity,league:LeagueSlug){const db=getDb();const now=new Date();const [user]=await db.insert(users).values({xUserId:profile.id,username:profile.username,displayName:profile.name,avatarUrl:profile.profileImageUrl,updatedAt:now}).onConflictDoUpdate({target:users.xUserId,set:{username:profile.username,displayName:profile.name,avatarUrl:profile.profileImageUrl,updatedAt:now}}).returning();const trialEndsAt=new Date(now.getTime()+7*24*60*60*1000);const [creator]=await db.insert(creators).values({userId:user.id,xUserId:profile.id,username:profile.username,displayName:profile.name,avatarUrl:profile.profileImageUrl,bio:profile.description,location:profile.location,followers:profile.followers,league,plan:"trial",subscriptionStatus:"trialing",trackingActive:true,trialEndsAt,updatedAt:now}).onConflictDoUpdate({target:creators.xUserId,set:{username:profile.username,displayName:profile.name,avatarUrl:profile.profileImageUrl,bio:profile.description,location:profile.location,followers:profile.followers,league,updatedAt:now}}).returning();return{user,creator};}
export async function getCreatorByUserId(userId:string){const [creator]=await getDb().select().from(creators).where(eq(creators.userId,userId)).limit(1);return creator??null;}
export async function getCreatorProfileFromDb(username:string):Promise<CreatorProfile|null>{const db=getDb();const clean=username.replace(/^@/,"");const [row]=await db.select({id:creators.id,username:creators.username,displayName:creators.displayName,avatarUrl:creators.avatarUrl,bio:creators.bio,location:creators.location,currentFollowers:creators.followers,league:creators.league,plan:creators.plan,productName:products.name,productUrl:products.url,productDescription:products.description}).from(creators).leftJoin(products,and(eq(products.creatorId,creators.id),eq(products.isPrimary,true))).where(eq(creators.username,clean)).limit(1);if(!row)return null;const cutoff=new Date();cutoff.setUTCDate(cutoff.getUTCDate()-30);const historyRows=await db.select().from(snapshots).where(and(eq(snapshots.creatorId,row.id),gte(snapshots.snapshotDate,cutoff))).orderBy(desc(snapshots.snapshotDate));const history=historyRows.slice().reverse().map((item,index,list)=>({date:item.snapshotDate.toISOString().slice(5,10),followers:item.followers,change:index===0?0:item.followers-list[index-1].followers}));const baseline=history.length>1?history[Math.max(0,history.length-8)].followers:row.currentFollowers;const gain=row.currentFollowers-baseline;return{id:row.id,username:row.username,displayName:row.displayName,avatarUrl:row.avatarUrl,currentFollowers:row.currentFollowers,gain,rank:null,growthPercent:Number((baseline>0?gain/baseline*100:0).toFixed(1)),league:row.league as LeagueSlug,plan:row.plan as Plan,productName:row.productName,productUrl:row.productUrl,productDescription:row.productDescription,bio:row.bio,location:row.location,history};}
export async function getTrackableCreators(){const rows=await getDb().select().from(creators).where(eq(creators.trackingActive,true));const now=new Date();return rows.filter(c=>c.plan!=="trial"||Boolean(c.trialEndsAt&&c.trialEndsAt>=now));}
export async function updateCreatorFollowerCount(input:{creatorId:string;followers:number;league:LeagueSlug;profileImageUrl:string|null;displayName:string;username:string}){await getDb().update(creators).set({followers:input.followers,league:input.league,avatarUrl:input.profileImageUrl,displayName:input.displayName,username:input.username,updatedAt:new Date()}).where(eq(creators.id,input.creatorId));}
